#PUT ADAPTERS HERE FOR OTHER MODULES 

report_field='Reads with adapters:'

class Adapters:
    lab0 = "AATGATACGGCGACCACCGAGATCTACACXXXXXXXXACACTCTTTCCCTACACGACGCTCTTCCGATCT"
    lab1 = "GATCGGAAGAGCACACGTCTGAACTCCAGTCACXXXXXXXXATCTCGTATGCCGTCTTCTGCTTG"
    insert_re = '([ATCG]{5,8})'
    replace = "XXXXXXXX"
